# version: '3.7'
services:
  # database:
  #   container_name: fish-database
  #   build: ./database
  #   restart: unless-stopped
  #   volumes:
  #     - database-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - fish
  #   env_file: ./secrets/.env

  cent-backend:
    container_name: centflow-backend
    build:
      context: ./Backend/
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - 5002:5000
    volumes:
      - ./Backend/code:/var/opt/centflow
      - ./Backend/main.log:/var/opt/centflow/main.log
    networks:
      - fisheye_fish
    env_file: ./secrets/.env

  cent-frontend:
    container_name: centflow-frontend
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
     - 8889:80
    #  - 443:443
    #  - host:container
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - fisheye_fish

name: centflow
networks:
  fisheye_fish:
    external: true

volumes:
  database-data:
